project_name: pgxman
builds:
  - ldflags:
      - -s -w -X github.com/pgxman/pgxman.Version={{.Version}}
    goos: [darwin, linux]
    goarch: ["386", "amd64", "arm", "arm64"]
    env:
      - CGO_ENABLED=0
    id: pgxman
    binary: bin/pgxman
    main: ./cmd/pgxman
archives:
  - id: archive
    builds: [pgxman]
    name_template: '{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    wrap_in_directory: false
    format: tar.gz
    files:
      - LICENSE*
      - README*
      - CHANGELOG*
      - docs/man/*
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"
release:
  prerelease: auto
  name_template: "pgxman {{.Version}}"
  mode: append
  footer: |
    ## Docker images

    To pull the builder image, you can execute the following command:
    ```
    docker pull ghcr.io/pgxman/builder/debian/bookworm:{{ .Tag }}
    docker pull ghcr.io/pgxman/builder/ubuntu/jammy:{{ .Tag }}
    ````

    To pull the runner image, you can execute the following command:
    ```
    docker pull ghcr.io/pgxman/runner/postgres/16:{{ .Tag }}
    docker pull ghcr.io/pgxman/runner/postgres/15:{{ .Tag }}
    docker pull ghcr.io/pgxman/runner/postgres/14:{{ .Tag }}
    docker pull ghcr.io/pgxman/runner/postgres/13:{{ .Tag }}
    ````
changelog:
  skip: true
nfpms: #build:linux
  - license: Apache-2.0
    maintainer: Owen Ou <o@hydra.so>
    homepage: https://github.com/pgxman/pgxman
    bindir: /usr
    dependencies:
      - git
    description: PostgreSQL Extensions Manager
    file_name_template: '{{ .PackageName }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    formats:
      - deb
      - rpm
brews:
  - repository:
      owner: pgxman
      name: homebrew-tap
      token: "{{ .Env.CI_GITHUB_TOKEN }}"
    commit_author:
      name: Owen Ou
      email: o@hydra.so
    homepage: https://github.com/pgxman/pgxman
    description: PostgreSQL Extensions Manager
    folder: Formula
    license: "Apache 2.0"
    custom_block: |
      head "https://github.com/pgxman/pgxman.git"
    dependencies:
      - git
    install: |
      bin.install "bin/pgxman"
      man1.install Dir["docs/man/man1/pgxman*.1"]
      generate_completions_from_executable(bin/"pgxman", "completion")
    test: |
      assert_match(/pgxman version/, shell_output("#{bin}/pgxman --version"))
