project_name: pgxman
builds:
  - <<: &build_defaults
      ldflags:
        - -s -w -X github.com/hydradatabase/pgxman/pgxm.Version={{.Version}}
      goos: [darwin, linux]
      goarch: ["386", "amd64", "arm", "arm64"]
      env:
        - CGO_ENABLED=0
    id: pgxman
    binary: bin/pgxman
    main: ./cmd/pgxman
archives:
  - id: archive
    builds: [pgxman]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: false
    rlcp: true
    format: tar.gz
    files:
      - LICENSE*
      - README*
      - CHANGELOG*
      - etc/*
      - docs/pgxman/*
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"
release:
  prerelease: auto
  draft: true
  name_template: "PGXMan {{.Version}}"
nfpms: #build:linux
  - license: Apache-2.0
    maintainer: Owen Ou <o@hydra.so>
    homepage: https://github.com/pgxman/pgxman
    bindir: /usr
    dependencies:
      - docker.io
    description: PostgreSQL Extensions Manager
    formats:
      - deb
      - rpm
brews:
  - tap:
      owner: pgxman
      name: homebrew-pgxman
      token: "{{ .Env.CI_GITHUB_TOKEN }}"
    # TODO: remove after pgxman is public
    download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy
    commit_author:
      name: Owen Ou
      email: o@hydra.so
    homepage: https://github.com/pgxman/pgxman
    description: PostgreSQL Extensions Manager
    folder: Formula
    license: "Apache 2.0"
    custom_block: |
      head "https://github.com/pgxman/pgxman.git"
    install: |
      bin.install "bin/pgxman"
    test: |
      assert_match(/pgxman version/, shell_output("#{bin}/pgxman --version"))
