project_name: pgxman
builds:
  - ldflags:
      - -s -w -X github.com/pgxman/pgxman.Version={{.Version}}
    goos: [darwin, linux]
    goarch: ["386", "amd64", "arm", "arm64"]
    env:
      - CGO_ENABLED=0
    id: pgxman
    binary: bin/pgxman
    main: ./cmd/pgxman
archives:
  - id: archive
    builds: [pgxman]
    name_template: '{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    wrap_in_directory: false
    format: tar.gz
    files:
      - LICENSE*
      - README*
      - CHANGELOG*
      - docs/man/*
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"
release:
  prerelease: auto
  name_template: "pgxman {{.Version}}"
  mode: append
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^script:"
      - "^go.mod:"
      - "^.github:"
      - Merge branch
nfpms: #build:linux
  - license: Apache-2.0
    maintainer: Owen Ou <o@hydra.so>
    homepage: https://github.com/pgxman/pgxman
    bindir: /usr
    description: PostgreSQL Extensions Manager
    file_name_template: '{{ .PackageName }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    formats:
      - deb
      - rpm
brews:
  - repository:
      owner: pgxman
      name: homebrew-tap
      token: "{{ .Env.CI_GITHUB_TOKEN }}"
    commit_author:
      name: Owen Ou
      email: o@hydra.so
    homepage: https://github.com/pgxman/pgxman
    description: PostgreSQL Extensions Manager
    folder: Formula
    license: "Apache 2.0"
    custom_block: |
      head "https://github.com/pgxman/pgxman.git"
    install: |
      bin.install "bin/pgxman"
      man1.install Dir["docs/man/man1/pgxman*.1"]
      generate_completions_from_executable(bin/"pgxman", "completion")
    test: |
      assert_match(/pgxman version/, shell_output("#{bin}/pgxman --version"))
