version: '3'
name: {{ .ServiceName }}
services:
  {{ .ServiceName }}:
    container_name: pg_{{ .PGVersion }}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - {{ .Port }}:5432
    environment:
      - POSTGRES_USER={{ .PGUser }}
      - POSTGRES_PASSWORD={{ .PGPassword }}
      - POSTGRES_DB={{ .PGDatabase }}
    volumes:
      - {{ .DataDir }}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U {{ .PGUser }}"]
      interval: 5s
      timeout: 5s
      retries: 5
