version: '3'
name: {{ .ContainerName }}
services:
  {{ .ContainerName }}:
    container_name: {{ .ContainerName }}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PGXMAN_PACK_INSTALL_ARGS={{ .PackInstallArgs }}
    ports:
      - {{ .Postgres.Port }}:5432
    environment:
      - POSTGRES_USER={{ .Postgres.Username }}
      - POSTGRES_PASSWORD={{ .Postgres.Password }}
      - POSTGRES_DB={{ .Postgres.DBName }}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U {{ .Postgres.Username }}"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pg_data:
