FROM postgres:15

WORKDIR /src

RUN apt update && apt install -y curl git

COPY dist /tmp/dist
COPY install.sh /tmp/install.sh

RUN cat <<EOS > /tmp/pgxman.yaml
apiVersion: v1
pgVersions: [15]
extensions:
  - name: "pgvector"
    version: "0.4.4"
EOS
RUN PGXMAN_DOWNLOAD_URL=file:///tmp/dist sh /tmp/install.sh /tmp/pgxman.yaml

RUN pgxman --version
