# syntax=docker/dockerfile:1

FROM ubuntu AS merge

ARG WORKSPACE_DIR

{{- if .ExportDebianBookwormArtifacts }}
{{- range .PGVersions }}
COPY --from=debian-bookworm ${WORKSPACE_DIR}/target/{{ . }}/*.deb  /out/debian/bookworm/
{{- end }}
{{- end }}

{{- if .ExportUbuntuJammyArtifacts }}
{{- range .PGVersions }}
COPY --from=ubuntu-jammy ${WORKSPACE_DIR}/target/{{ . }}/*.deb  /out/ubuntu/jammy/
{{- end }}
{{- end }}

FROM ubuntu AS export

COPY --from=merge /out/ .
