# syntax=docker/dockerfile:1

FROM ubuntu AS merge

COPY --from=debian-bookworm /workspace/target/*.deb  /out/debian/bookworm/
COPY --from=ubuntu-jammy /workspace/target/*.deb  /out/ubuntu/jammy/

FROM ubuntu AS export

COPY --from=merge /out/ .
