#!/usr/bin/env bash

set -eo pipefail

echo "---> pgvector buildkit"

git clone --branch v0.4.2 https://github.com/pgvector/pgvector
cd pgvector
DESTDIR=${DESTDIR} make
DESTDIR=${DESTDIR} make install
