.nh
.TH "pgxman" "1" "Feb 2024" "pgxman" "PostgreSQL Extension Manager"

.SH NAME
.PP
pgxman-pack-install - Install PostgreSQL extensions from a pack file


.SH SYNOPSIS
.PP
\fBpgxman pack install [flags]\fP


.SH DESCRIPTION
.PP
Install PostgreSQL extensions based on a specified pack file (e.g., pgxman.yaml).
This ensures consistency across extensions by synchronizing them with the definitions provided in the pack file.


.SH OPTIONS
.PP
\fB-f\fP, \fB--file\fP="/src/pgxman.yaml"
	The pack file to use.

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for install

.PP
\fB-y\fP, \fB--yes\fP[=false]
	Automatic yes to prompts and run install non-interactively.


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--debug\fP[=false]
	enable debug logging

.PP
\fB--registry\fP="https://registry.pgxman.com/v1"
	registry URL


.SH EXAMPLE
.EX
  # Install extensions from the pgxman.yaml file in the current directory
  pgxman pack install

  # Suppress prompts for automatic installation or upgrade
  pgxman pack install -y

  # Specify a different location for the pgxman.yaml file
  pgxman pack install -f /PATH_TO/pgxman.yaml

  # Read the pgxman.yaml file from STDIN
  cat <<EOF | pgxman pack install -f -
    apiVersion: v1
    extensions:
      - name: "pgvector"
        version: "0.5.0"
      - path: "/local/path/to/extension"
    postgres:
      version: "14"
  EOF
  

.EE


.SH SEE ALSO
.PP
\fBpgxman-pack(1)\fP
