.nh
.TH "pgxman" "1" "Feb 2024" "pgxman" "PostgreSQL Extension Manager"

.SH NAME
.PP
pgxman-build - Build extension according to the configuration file


.SH SYNOPSIS
.PP
\fBpgxman build [flags]\fP


.SH DESCRIPTION
.PP
Build extension according to the configuration file


.SH OPTIONS
.PP
\fB--cache-from\fP=[]
	External cache sources. The value is passed to docker buildx build --cache-from.

.PP
\fB--cache-to\fP=[]
	Cache export destinations. The value is passed to docker buildx build --cache-to.

.PP
\fB-f\fP, \fB--file\fP="extension.yaml"
	Path to the extension manifest file

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for build

.PP
\fB--no-cache\fP[=false]
	Do not use cache when building the image. The value is passed to docker buildx build --no-cache.

.PP
\fB--parallel\fP=2
	Number of parrallel builds to run

.PP
\fB-s\fP, \fB--set\fP=[]
	Override values in the extension.yaml file in the format of --set KEY=VALUE, e.g. --set version=1.0.0 --set arch=[amd64,arm64] --set pgVersions=[10,11,12]


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--debug\fP[=false]
	enable debug logging

.PP
\fB--registry\fP="https://registry.pgxman.com/v1"
	registry URL


.SH SEE ALSO
.PP
\fBpgxman(1)\fP
