.nh
.TH "pgxman" "1" "Nov 2023" "pgxman" "PostgreSQL Extension Manager"

.SH NAME
.PP
pgxman-doctor - Troubleshoot your system for potential problems


.SH SYNOPSIS
.PP
\fBpgxman doctor [flags]\fP


.SH DESCRIPTION
.PP
Check your system for potential problems. Will exit with a non-zero status if any potential problems are found.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for doctor


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--debug\fP[=false]
	enable debug logging


.SH SEE ALSO
.PP
\fBpgxman(1)\fP
