.nh
.TH "pgxman" "1" "Nov 2023" "pgxman" "PostgreSQL Extension Manager"

.SH NAME
.PP
pgxman-pack - Manage PostgreSQL extensions from a pack file


.SH SYNOPSIS
.PP
\fBpgxman pack [flags]\fP


.SH DESCRIPTION
.PP
Manage PostgreSQL extensions from a pack file


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for pack


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--debug\fP[=false]
	enable debug logging


.SH SEE ALSO
.PP
\fBpgxman(1)\fP, \fBpgxman-pack-install(1)\fP
