.nh
.TH "pgxman" "1" "Feb 2024" "pgxman" "PostgreSQL Extension Manager"

.SH NAME
.PP
pgxman-container-teardown - Tear down a container


.SH SYNOPSIS
.PP
\fBpgxman container teardown [flags]\fP


.SH DESCRIPTION
.PP
Tear down a container and purge all data.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for teardown


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--debug\fP[=false]
	enable debug logging

.PP
\fB--registry\fP="https://registry.pgxman.com/v1"
	registry URL


.SH EXAMPLE
.EX
 # Tear down the PostgreSQL 15 playgrond container.
pgxman container teardown pgxman_runner_15

# Tear down the PostgreSQL 15 & 16 containers.
pgxman container teardown pgxman_runner_15 pgxman_runner_16


.EE


.SH SEE ALSO
.PP
\fBpgxman-container(1)\fP
