.nh
.TH "pgxman" "1" "Nov 2023" "pgxman dev" "PostgreSQL Extension Manager"

.SH NAME
.PP
pgxman-bundle - Manage PostgreSQL extensions from a bundle file


.SH SYNOPSIS
.PP
\fBpgxman bundle [flags]\fP


.SH DESCRIPTION
.PP
Install or upgrade PostgreSQL extensions based on a specified bundle file (e.g., pgxman.yaml).
This ensures consistency across extensions by synchronizing them with the definitions provided in the bundle file.


.SH OPTIONS
.PP
\fB-f\fP, \fB--file\fP=""
	The pgxman.yaml file to use. Defaults to pgxman.yaml in the current directory.

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for bundle

.PP
\fB--sudo\fP[=false]
	Run the underlaying package manager command with sudo.

.PP
\fB-y\fP, \fB--yes\fP[=false]
	Automatic yes to prompts and run install non-interactively.


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--debug\fP[=false]
	enable debug logging


.SH EXAMPLE
.EX
  # Install or upgrade extensions from the pgxman.yaml file in the current directory
  pgxman bundle

  # Suppress prompts for automatic installation or upgrade
  pgxman bundle -y

  # Specify a different location for the pgxman.yaml file
  pgxman bundle -f /PATH_TO/pgxman.yaml

  # Read the pgxman.yaml file from STDIN
  cat <<EOF | pgxman bundle -f -
    apiVersion: v1
    extensions:
      - name: "pgvector"
        version: "0.5.0"
      - path: "/local/path/to/extension"
    postgres:
      version: "14"
  EOF
  

.EE


.SH SEE ALSO
.PP
\fBpgxman(1)\fP


.SH HISTORY
.PP
15-Nov-2023 Auto generated by spf13/cobra
