FROM postgres:15

ENV DEBIAN_FRONTEND noninteractive
ARG USER=myuser
ARG UID=1000
ARG GID=100

RUN apt update && apt install -y curl sudo

RUN useradd -m -s /bin/bash -N -u $UID $USER && \
  echo "${USER} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
  chmod 0440 /etc/sudoers && \
  chmod g+w /etc/passwd

USER ${USER}
ENV USER ${USER}
ENV HOME /home/${USER}
WORKDIR /home/${USER}

COPY install.sh /tmp/install.sh
COPY dist /tmp/dist

RUN cat <<EOS > /tmp/pgxman.yaml
apiVersion: v1
postgres:
  version: "15"
extensions:
  - name: pgvector
  - name: postgis
  - name: parquet_s3_fdw
EOS
RUN bash -c "PGXMAN_INSTALLER_DEBIAN_PACKAGE_DIR=/tmp/dist /tmp/install.sh /tmp/pgxman.yaml"
