# syntax=docker/dockerfile:1

FROM postgres_base

ARG DEBIAN_FRONTEND=noninteractive

RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
    ca-certificates \
    git \
    ; \
    apt-get clean

COPY --from=pgxman /go/bin/* /usr/local/bin/
