# syntax=docker/dockerfile:1

FROM postgres_base

ARG DEBIAN_FRONTEND=noninteractive

RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
    ca-certificates \
    git \
    ; \
    apt-get clean

RUN set -eux; \
    locale-gen en_US.UTF-8; \
    echo "LC_ALL=en_US.UTF-8" >> /etc/environment; \
    echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen; \
    echo "LANG=en_US.UTF-8" > /etc/locale.conf

COPY --from=pgxman /go/bin/* /usr/local/bin/
