# syntax=docker/dockerfile:1

FROM postgres_base

ARG DEBIAN_FRONTEND=noninteractive
ARG ALLOW_INSECURE_APT=0

RUN set -eux; \
    if [ "$ALLOW_INSECURE_APT" = "1" ]; then \
        printf '%s\n' \
            'Acquire::AllowInsecureRepositories "true";' \
            'Acquire::AllowDowngradeToInsecureRepositories "true";' \
            'APT::Get::AllowUnauthenticated "true";' \
            > /etc/apt/apt.conf.d/99pgxman-allow-insecure; \
    fi; \
    APT_CACHE_DIR=$(mktemp -d); \
    apt-get -o Dir::Cache::archives="${APT_CACHE_DIR}" update; \
    apt-get -o Dir::Cache::archives="${APT_CACHE_DIR}" install -y --no-install-recommends \
    ca-certificates \
    git \
    ; \
    rm -rf "${APT_CACHE_DIR}"; \
    apt-get clean; \
    if [ "$ALLOW_INSECURE_APT" = "1" ]; then rm -f /etc/apt/apt.conf.d/99pgxman-allow-insecure; fi

RUN set -eux; \
    locale-gen en_US.UTF-8; \
    echo "LC_ALL=en_US.UTF-8" >> /etc/environment; \
    echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen; \
    echo "LANG=en_US.UTF-8" > /etc/locale.conf

COPY --from=pgxman /go/bin/* /usr/local/bin/
