name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          check-latest: true
      - name: Run build
        run: |
          make build
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          check-latest: true
      - name: Run tests
        run: |
          make test
  vet:
    name: Vet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          check-latest: true
      - name: Run vet
        run: |
          make vet
  e2etest:
    name: E2Etest
    needs: [build, test, vet]
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          check-latest: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host
      - name: Build and push to local registry
        uses: docker/build-push-action@v4
        with:
          push: true
          pull: true
          context: .
          tags: localhost:5000/pgxman/builder:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Run e2etest
        run: |
          E2ETEST_BUILD_IMAGE=localhost:5000/pgxman/builder make e2etest
  docker:
    name: Docker
    needs: [e2etest]
    uses: ./.github/workflows/docker.yaml
    secrets: inherit
