name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          check-latest: true
      - name: Run build
        run: |
          make build
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          check-latest: true
      - name: Run tests
        run: |
          make test
  vet:
    name: Vet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          check-latest: true
      - name: Run vet
        run: |
          make vet
  e2etest:
    name: E2Etest
    needs: [build, test, vet]
    runs-on: ubuntu-latest
    env:
      DEBIAN_BOOKWORM_IMAGE: localhost:5000/pgxman/builder/debian/bookworm:dev
      UBUNTU_JAMMY_IMAGE: localhost:5000/pgxman/builder/ubuntu/jammy:dev
      RUNNER_POSTGRES_15_IMAGE: localhost:5000/pgxman/runner/postgres/15:dev
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          check-latest: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      - name: Build and push to local registry
        uses: docker/bake-action@v4
        with:
          push: true
          pull: true
          files: |
            dockerfiles/docker-bake.hcl
          targets: |
            builder-debian-bookworm
            builder-ubuntu-jammy
            runner-postgres-15
          set: |
            *.platform=linux/amd64
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
            builder-debian-bookworm.tags=${{ env.DEBIAN_BOOKWORM_IMAGE }}
            builder-ubuntu-jammy.tags=${{ env.UBUNTU_JAMMY_IMAGE }}
            runner-postgres-15.tags=${{ env.RUNNER_POSTGRES_15_IMAGE }}
      - name: Run e2etest
        run: |
          make e2etest
  installer_test:
    name: Installer Test
    needs: [build, test, vet]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          check-latest: true
      - name: Run tests
        run: |
          make tools installer_test
  mac_install_test:
    name: Mac Install Test
    needs: [build, test, vet]
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          check-latest: true
      - name: Run tests
        run: |
          brew install docker docker-compose docker-buildx colima
          mkdir -p ~/.docker/cli-plugins
          ln -sfn $(brew --prefix docker-compose)/bin/docker-compose ~/.docker/cli-plugins/docker-compose
          ln -sfn $(brew --prefix docker-buildx)/bin/docker-buildx ~/.docker/cli-plugins/docker-buildx
          colima start

          make build docker_load_runner
          bin/pgxman doctor
          bin/pgxman install pgvector --debug
  docker:
    name: Docker
    needs: [e2etest, installer_test, mac_install_test]
    uses: ./.github/workflows/docker.yaml
    secrets: inherit
