name: Docker
on:
  workflow_call:
  workflow_dispatch:
jobs:
  docker:
    name: Docker
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - amd64
          - arm64
        include:
          - platform: amd64
            runs-on: ubuntu-22.04
          - platform: arm64
            runs-on: buildjet-4vcpu-ubuntu-2204-arm
    steps:
      - uses: actions/checkout@v3
      - name: Generate build meta
        run: |
          # tag > commit
          echo "build_version=$(git describe --tags --exact-match 2> /dev/null || git rev-parse --short HEAD)" >> "$GITHUB_ENV"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/pgxman/builder
      - name: Docker build and push
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.event_name != 'pull_request' }}
          pull: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/${{ matrix.platform }}
          cache-from: type=registry,ref=ghcr.io/pgxman/builder-cache:${{ matrix.platform }}
          cache-to: type=registry,ref=ghcr.io/pgxman/builder-cache:${{ matrix.platform }},mode=max
          build-args: |
            BUILD_VERSION=${{ env.build_version }}
