name: Release
on:
  workflow_call:
  workflow_dispatch:
  push:
    tags:
      - "v*"
jobs:
  docker:
    name: Docker
    uses: ./.github/workflows/docker.yaml
    secrets: inherit
  goreleaser:
    name: GoReleaser
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
      - name: Generate tag name
        run: |
          # tag > commit
          echo "build_version=$(git describe --tags --exact-match 2> /dev/null || git rev-parse --short HEAD)" >> "$GITHUB_ENV"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI_GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: ${{ env.build_version }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      - name: Install deb-s3
        run: |
          gem install deb-s3
      - name: Import GPG Key
        env:
          GPG_PRIVATE: ${{ secrets.GPG_PRIVATE }}
          GPG_PUBLIC: ${{ secrets.GPG_PUBLIC }}
        run: |
          echo -e "$GPG_PRIVATE" | gpg --import --no-tty --batch --yes
          echo -e "$GPG_PUBLIC" | gpg --import --no-tty --batch --yes
          echo "allow-preset-passphrase" > ~/.gnupg/gpg-agent.conf
          gpg-connect-agent RELOADAGENT /bye
      - name: Upload debian package
        env:
          AWS_DEBIAN_S3_BUCKET: ${{ secrets.AWS_DEBIAN_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GPG_SIGNING_KEY_ID: C9ADBB93237BCD3B
        run: |
          script/deb-s3-upload "./dist/pgxman_*.deb"
      - name: Upload install script
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GORELEASER_CURRENT_TAG: ${{ env.build_version }}
        run: |
          gh release upload "${GORELEASER_CURRENT_TAG}" "$PWD/install.sh" -R pgxman/pgxman --clobber
  linux_install_test:
    name: Linux Install Test
    needs: [docker, goreleaser]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pg 15
        run: |
          sudo ./script/install-pg-linux 15
      - name: Run tests
        run: |
          cat <<EOS > /tmp/pgxman.yaml
          apiVersion: v1
          postgres:
            version: "15"
          extensions:
            - name: pgvector
            - name: postgis
            - name: parquet_s3_fdw
          EOS
          ./install.sh /tmp/pgxman.yaml
          sudo pgxman install pg_ivm pg_bm25 --debug
  mac_install_test:
    name: Mac Install Test
    needs: [docker, goreleaser]
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: douglascamata/setup-docker-macos-action@main
      - name: Setup Docker buildx
        run: |
          brew install docker-buildx
          mkdir -p ~/.docker/cli-plugins
          ln -sfn "$(brew --prefix docker-buildx)/bin/docker-buildx" ~/.docker/cli-plugins/docker-buildx
      - name: Run tests
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}
          HOMEBREW_GITHUB_PACKAGES_TOKEN: ${{ github.token }}
          HOMEBREW_GITHUB_PACKAGES_USER: ${{ github.actor }}
          HOMEBREW_NO_AUTO_UPDATE: 1
        run: |
          ./install.sh
          pgxman install pgvector postgis parquet_s3_fdw --debug
